pushing finalized files for review
egkirpichev/FE-78-learning-front-end-development pull request #2
Opened 2022-02-20 08:10 UTC by egkirpichev

Completed home task №2: compiled navigation block and first content block
Figma project: https://www.figma.com/file/16bdlWFoZXXIpyyZmwy9JU/Logoipsum?node-id=1%3A2

![image](https://user-images.githubusercontent.com/99477750/154834043-99ab34b9-fa77-48ab-b68a-b69d722372f4.png) 
![image](https://user-images.githubusercontent.com/99477750/154834072-62cd657c-ab16-4617-9591-bcff0174b079.png)

2022-02-20 11:25 UTC, shuliakleonid requested changes

2022-02-20 11:25 UTC, shuliakleonid commented on style.css
> +	background-color:#FFFFFF;
if your font does not load the browser, you should say what family fond is.

2022-02-20 11:25 UTC, shuliakleonid commented on style.css
> +	font-size: 20px;
font-family --> sans-serif

2022-02-20 15:53 UTC, shuliakleonid approved these changes

2022-02-21 08:59 UTC, AlexisKozlov approved these changes
Good title name your homework  :)

2022-02-22 05:54 UTC, KseniaKotova approved these changes

2022-02-22 07:32 UTC, merged